name: Fetch LSX Trades and Create Release

on:
  schedule:
    - cron: '0 1 * * *'  # Läuft täglich um 1:00 UTC
  workflow_dispatch:     # Ermöglicht manuelle Ausführung

permissions:
  contents: write      # Gibt Schreibrechte für Repository-Inhalte

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch
        run: |
          BRANCH_NAME="lsx-trades-$(date -d 'yesterday' +%Y-%m-%d)"
          git checkout -b $BRANCH_NAME
        env:
          TZ: UTC

      - name: Fetch LSX trades data
        run: |
          YESTERDAY=$(date -d 'yesterday' +%Y-%m-%d)
          curl -s "https://www.ls-x.de/_rpc/json/.lstc/instrument/list/lsxtradesyesterday" | gzip > "lsx_trades_${YESTERDAY}.csv.gz"

      - name: Commit and push changes
        run: |
          YESTERDAY=$(date -d 'yesterday' +%Y-%m-%d)
          git add "lsx_trades_${YESTERDAY}.csv.gz"
          git commit -m "Add LSX trades data for ${YESTERDAY}"
          git push origin HEAD

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="lsx-trades-$(date -d 'yesterday' +%Y-%m-%d)"
          YESTERDAY=$(date -d 'yesterday' +%Y-%m-%d)
          gh release create "v${YESTERDAY}" \
            --title "LSX Trades ${YESTERDAY}" \
            --target "$BRANCH_NAME" \
            "lsx_trades_${YESTERDAY}.csv.gz"

      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="lsx-trades-$(date -d 'yesterday' +%Y-%m-%d)"
          gh api -X DELETE \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/git/refs/heads/${BRANCH_NAME}"
